#ifndef PRAGUEUI_GLOBAL_H
#define PRAGUEUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PRAGUEUI_LIBRARY)
#  define PRAGUEUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define PRAGUEUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PRAGUEUI_GLOBAL_H
